ATTACK_RETRY_DELAY_MS = 90
HUNT_RETRY_DELAY_MS = 450
UNKNOWN_SCREEN_BACK_DELAY_MS = 1000
GAME_ENTRY_URL = "https://3kingdoms.ru/main.php"
RETURN_TO_LOCATION_POINT = (0.90, 0.20)
SCREEN_SYNC_INTERVAL_MS = 50
JS_VISIBLE_ATTACK_INTERVAL_MS = 450
JS_BATTLE_PROBE_INTERVAL_MS = 450
