from __future__ import annotations

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
MODULE_DIR = ROOT / "browser_injector" / "page_bridge_modules"
OUTPUT = ROOT / "browser_injector" / "page_bridge.js"
MODULES = (
    "00_core_combat.js",
    "10_hunt_inventory.js",
    "20_hunt_actions.js",
    "30_navigation_death.js",
    "40_state_layout_dispatch.js",
)


def build() -> str:
    sections = [
        "// Generated by scripts/build_page_bridge.py. Edit page_bridge_modules instead.\n",
        "(() => {\n",
    ]
    for module_name in MODULES:
        module_path = MODULE_DIR / module_name
        sections.append(f"  // source: page_bridge_modules/{module_name}\n")
        sections.append(module_path.read_text(encoding="utf-8").rstrip() + "\n")
    sections.append("})();\n")
    return "".join(sections)


def main() -> int:
    output = build()
    OUTPUT.write_text(output, encoding="utf-8")
    print(f"built {OUTPUT.relative_to(ROOT)} from {len(MODULES)} modules")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
